# Importing all the Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression

# Importing the dataset
Link:
https://raw.githubusercontent.com/omairaasim/machine_learning/master/project_11_k_nearest_neighbor/iphone_purchase_records.csv

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/omairaasim/machine_learning/master/project_11_k_nearest_neighbor/iphone_purchase_records.csv")

# Data Analysis

In [ ]:
df.head()

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [ ]:
df.tail()

Gender  Age  Salary  Purchase Iphone
395  Female   46   41000                1
396    Male   51   23000                1
397  Female   50   20000                1
398    Male   36   33000                0
399  Female   49   36000                1

In [ ]:
df.shape

(400, 4)

In [ ]:
df.describe()

Age         Salary  Purchase Iphone
count  400.000000     400.000000       400.000000
mean    37.655000   69742.500000         0.357500
std     10.482877   34096.960282         0.479864
min     18.000000   15000.000000         0.000000
25%     29.750000   43000.000000         0.000000
50%     37.000000   70000.000000         0.000000
75%     46.000000   88000.000000         1.000000
max     60.000000  150000.000000         1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   Salary           400 non-null    int64 
 3   Purchase Iphone  400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [ ]:
df.isnull().sum()

Gender             0
Age                0
Salary             0
Purchase Iphone    0
dtype: int64

In [ ]:
df.corr()

<ipython-input-9-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


Age    Salary  Purchase Iphone
Age              1.000000  0.155238         0.622454
Salary           0.155238  1.000000         0.362083
Purchase Iphone  0.622454  0.362083         1.000000

In [ ]:
df.Gender.value_counts()

Female    204
Male      196
Name: Gender, dtype: int64

In [ ]:
df.loc[df['Purchase Iphone']==1,'Gender'].value_counts()

Female    77
Male      66
Name: Gender, dtype: int64

# Splitting of Data

In [ ]:
df.head(2)

Gender  Age  Salary  Purchase Iphone
0   Male   19   19000                0
1   Male   35   20000                0

Gender  Age  Salary  Purchase Iphone
0   Male   19   19000                0
1   Male   35   20000                0

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
x

Gender  Age  Salary
0      Male   19   19000
1      Male   35   20000
2    Female   26   43000
3    Female   27   57000
4      Male   19   76000
..      ...  ...     ...
395  Female   46   41000
396    Male   51   23000
397  Female   50   20000
398    Male   36   33000
399  Female   49   36000

[400 rows x 3 columns]

In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchase Iphone, Length: 400, dtype: int64

# Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
enc = LabelEncoder()

In [ ]:
x.Gender = enc.fit_transform(x.Gender)

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  400 non-null    int64
 1   Age     400 non-null    int64
 2   Salary  400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


# Splitting of Dataset

In [ ]:
skf = StratifiedKFold(n_splits=5)

In [ ]:
for train_index,test_index in skf.split(x,y):
  x_train,x_test = x.iloc[train_index],x.iloc[test_index]
  y_train,y_test = y.iloc[train_index],y.iloc[test_index]

# Feature Scaling

In [ ]:
scale = StandardScaler()

In [ ]:
x_train = scale.fit_transform(x_train)
x_test = scale.fit_transform(x_test)

In [ ]:
x_test

array([[ 1.        , -0.51982647,  0.49135807],
       [ 1.        , -0.94708111,  0.45312009],
       [ 1.        , -0.51982647, -0.04397368],
       [-1.        , -0.09257184,  2.70916104],
       [ 1.        , -0.8046629 ,  0.33840614],
       [ 1.        , -1.23191753, -0.04397368],
       [ 1.        ,  0.61951922,  3.0150649 ],
       [-1.        , -0.94708111, -0.0057357 ],
       [ 1.        , -0.37740826,  0.64431   ],
       [ 1.        , -0.94708111,  0.56783404],
       [-1.        , -1.23191753, -0.19692561],
       [-1.        , -1.08949932,  0.03250228],
       [ 1.        ,  0.19226459,  0.64431   ],
       [-1.        , -0.51982647, -0.08221166],
       [ 1.        , -0.23499005, -0.31163955],
       [-1.        ,  1.04677386,  2.74739902],
       [-1.        , -0.8046629 , -0.46459148],
       [-1.        , -0.23499005,  0.30016816],
       [-1.        , -0.8046629 , -0.46459148],
       [-1.        , -0.66224469,  0.64431   ],
       [ 1.        , -1.23191753, -0.273

# Model Selection

In [ ]:
log = LogisticRegression()
knn = KNeighborsClassifier()

# Training the model

In [ ]:
log.fit(x_train, y_train)
knn.fit(x_train, y_train)

KNeighborsClassifier()

# Testing the model

In [ ]:
y_knn_predict = knn.predict(x_test)

In [ ]:
y_log_predict = log.predict(x_test)

In [ ]:
new_df = pd.DataFrame({"Actual":y_test,"Predicted":y_knn_predict})

In [ ]:
new_df.head()

Actual  Predicted
266       0          0
267       0          0
269       0          0
270       0          1
276       0          0

# Performance

In [ ]:
confusion_matrix(y_test,y_knn_predict)

array([[46,  5],
       [ 7, 22]])

In [ ]:
confusion_matrix(y_test,y_log_predict)

array([[46,  5],
       [17, 12]])

In [ ]:
# Accuracy = (46+22)/80 =86%

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,y_knn_predict)

0.85

In [ ]:
accuracy_score(y_test,y_log_predict)

0.725

In [ ]:
lis = [i for i in range(2,101) if i%2!=0]

In [ ]:
acc=[]
dic = {}
for i in lis:
  knn = KNeighborsClassifier(n_jobs=i)
  knn.fit(x_train, y_train)
  y_knn_pred = knn.predict(x_test)
  acc.append(accuracy_score(y_test,y_knn_pred))
  dic[i] = accuracy_score(y_test,y_knn_pred)
print(max(acc))

0.85


In [ ]:
dic

{3: 0.85,
 5: 0.85,
 7: 0.85,
 9: 0.85,
 11: 0.85,
 13: 0.85,
 15: 0.85,
 17: 0.85,
 19: 0.85,
 21: 0.85,
 23: 0.85,
 25: 0.85,
 27: 0.85,
 29: 0.85,
 31: 0.85,
 33: 0.85,
 35: 0.85,
 37: 0.85,
 39: 0.85,
 41: 0.85,
 43: 0.85,
 45: 0.85,
 47: 0.85,
 49: 0.85,
 51: 0.85,
 53: 0.85,
 55: 0.85,
 57: 0.85,
 59: 0.85,
 61: 0.85,
 63: 0.85,
 65: 0.85,
 67: 0.85,
 69: 0.85,
 71: 0.85,
 73: 0.85,
 75: 0.85,
 77: 0.85,
 79: 0.85,
 81: 0.85,
 83: 0.85,
 85: 0.85,
 87: 0.85,
 89: 0.85,
 91: 0.85,
 93: 0.85,
 95: 0.85,
 97: 0.85,
 99: 0.85}

# Conclusion:
Hence ,we can conclude that using K- Neighbors Classifier the Accuracy of the model increases